2020-10-13 21:57:39.395 [error] <0.327.0> gen_server <0.327.0> terminated with reason: socket_closed_unexpectedly
2020-10-13 21:57:39.403 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-10-13 21:57:39.413 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.326.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.327.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-10-13 21:57:39.417 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.326.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.327.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-13 22:03:31.425 [error] <0.1956.0> gen_server <0.1956.0> terminated with reason: socket_closed_unexpectedly
2020-10-13 22:03:31.430 [error] <0.1956.0> CRASH REPORT Process <0.1956.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-10-13 22:03:31.432 [error] <0.1954.0> Supervisor {<0.1954.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1955.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.1956.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-10-13 22:03:31.432 [error] <0.1954.0> Supervisor {<0.1954.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1955.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.1956.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-13 22:07:30.116 [error] <0.297.0>@Elixir.GenRMQ.Consumer:handle_info:403 gen_server 'Elixir.ExampleConsumer' terminated with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403
2020-10-13 22:07:30.116 [error] <0.297.0>@Elixir.GenRMQ.Consumer:handle_info:403 CRASH REPORT Process 'Elixir.ExampleConsumer' with 1 neighbours crashed with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403
2020-10-13 22:07:30.117 [error] <0.317.0>@Elixir.GenRMQ.Consumer:handle_info:403 gen_server <0.317.0> terminated with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403
2020-10-13 22:07:30.117 [error] <0.317.0>@Elixir.GenRMQ.Consumer:handle_info:403 CRASH REPORT Process <0.317.0> with 0 neighbours exited with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403 in gen_server:decode_msg/9 line 432
2020-10-13 22:07:30.117 [error] <0.280.0>@Elixir.GenRMQ.Consumer:handle_info:403 gen_server 'Elixir.ExamplePublisher' terminated with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403
2020-10-13 22:07:30.117 [error] <0.280.0>@Elixir.GenRMQ.Consumer:handle_info:403 CRASH REPORT Process 'Elixir.ExamplePublisher' with 0 neighbours exited with reason: no match of right hand value nil in 'Elixir.GenRMQ.Consumer':handle_info/2 line 403 in gen_server:decode_msg/9 line 432
